defaults:
  - single
  - _self_

data:
  fold_dir: '/data/pathology/projects/ais-cap/dataset/witali-liver/splits'
  tiles_csv: '/data/pathology/projects/ais-cap/dataset/witali-liver/tiles.csv'

features_dir: 'output/witali-liver/features/2qi92y06/global/slide'
output_dir: 'output/witali-liver/survival'
experiment_name: 'concat_bs'
level: 'global'

nepochs: 50
label_name: 'OS'
nbins: 4

training:
  batch_size: 8

testing:
  retrieve_checkpoint: 'best'

model:
  agg_method: 'concat'
  slide_pos_embed:
    use: False
    learned: False
    type: '1d'
    max_seq_len: 220
    max_nslide: -1
    tile_size: ${model.region_size}

wandb:
  enable:
    False